language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_0f0742040902_key -iv $encrypted_0f0742040902_iv
  -in wang_rsa.enc -out ~/.ssh/wang_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - echo -e "Host 140.143.202.200\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
script:
- hexo g
after_script:
- cd ./public
- scp -o stricthostkeychecking=no   -r ./public root@140.143.202.200:/usr/share/nginx/html/
- git init
- git config user.name "WangGenzhen"
- git config user.email "1280210282@qq.com"
- git add .
- git commit -m "travis测试"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/WangGenzhen/WangGenzhen.github.io.git
